name: Vonage Go SDK

on:
  push: {}
  pull_request: {}

strategy:
  matrix:
    go: ["1.11", "1.12", "1.13", "1.14"]
jobs:
  lint:
    name: Standards checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go vet
      - uses: actions-contrib/golangci-lint@v1
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: go test -v
