name: Vonage Go SDK

on:
  push: {}
  pull_request: {}

jobs:
  lint:
    name: Standards checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: go vet
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: go test -v
